### ISSUE TITLE
Repetitive "address" info in Onyx template

### ISSUE THREAD

**Issue by jvel07** [Reactive-Resume/Reactive-Resume#548]
Awesome work! Just a little issue regarding the Onyx template: the address information is shown twice, one below the name and a second time at the top right corner. This looks a bit unaesthetic and repetitive. 
Other than that, this one and all your templates are amazing. Keep it up!

**Comment by jvel07** [comment]
Oh, btw, a toggle to include/remove entire sections would be a perfect fit!

**Comment by mupsys** [comment]
@AmruthPillai While I don't have the time to take care of adding the ability to customize this, I'm willing to open up a PR for this issue to remove the duplicate address. I just need to know if you want the Address block under the picture on the left side or the address with the location icon on the right.

**Comment by AmruthPillai** [comment]
Hey @mupsys , thanks a lot. Just below the picture would be fine, the one on the right can be removed.
